# Generated by Django 5.0 on 2024-08-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userimagemodel_delete_networkdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("prediction", models.CharField(max_length=50)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
